[VAL-4] Implement movie Projections
valconsee-internship/videotecha-ana pull request #4
Opened 2023-05-12 14:55 UTC by anagavrilovic

2023-05-12 14:55 UTC, anagavrilovic commented
![](https://github.trello.services/images/mini-trello-icon.png) [[VAL-4] Implement movie Projections](https://trello.com/c/fjF4pSvl/25-val-4-implement-movie-projections)

2023-05-18 08:43 UTC, bpaskali requested changes

2023-05-18 08:43 UTC, branko-paskali-valcon commented on src/main/java/com/example/videotecha/controller/AuthenticationController.java
> +        return new UserDto(authenticationService.register(user));
Since you already have userMapper, mapping could be done in that class instead of dto

2023-05-18 08:43 UTC, branko-paskali-valcon commented on src/main/java/com/example/videotecha/service/AuthenticationService.java
> +    User register(com.example.videotecha.dto.UserDto user);
Why remove import and add it explicitly like this?

2023-05-18 08:43 UTC, branko-paskali-valcon commented on src/main/java/com/example/videotecha/service/UserService.java
> +    User save(com.example.videotecha.dto.UserDto user);
Same here

2023-05-18 09:02 UTC, srdjan-popovic requested changes
Please take a look at the comments. If there's any question let me know.

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/mapper/ProjectionMapper.java
> +    public static List<ProjectionDto> projectionsToProjectionDto(List<Projection> projections) {
If you already named `moviesToMovieDtos` you should also name this `projectionsToProjectionDtos`.

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/repository/ProjectionRepository.java
> +    List<Projection> findAllAvailableProjections();
You're already in `ProjectionRepository`, you don't need to name this `findAllAvailableProjections`, you could name it `findAllAvailable`.

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/service/AuthenticationService.java
> +    User register(com.example.videotecha.dto.UserDto user);
Same question as @bpaskali .

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/service/ProjectionService.java
> +    List<Projection> findAllAvailableProjections();
Same comment as in `ProjectionRepository`, you can rename it to `findAllAvailable`.

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/service/impl/AuthenticationServiceImpl.java
> +    public User register(com.example.videotecha.dto.UserDto user) {
Same comment for imports. Do you have a reason why do you do it this way?

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/service/impl/ProjectionServiceImpl.java
> +            // (StartA <= EndB) and (EndA >= StartB)
Please remove comments from the code.

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/service/impl/ProjectionServiceImpl.java
> +                    && newProjection.getEndDateAndTime().isAfter(existingProjection.getStartDateAndTime())) {
We'll have a discussion about this.

2023-05-18 09:02 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/service/impl/UserServiceImpl.java
> +    public User save(com.example.videotecha.dto.UserDto user) {
Same comment about imports.

2023-05-18 12:05 UTC, srdjan-popovic approved these changes
LGTM

2023-05-18 12:05 UTC, srdjan-popovic commented on src/main/java/com/example/videotecha/service/impl/ProjectionServiceImpl.java
> +                    && newProjection.getEndDateAndTime().isAfter(existingProjection.getStartDateAndTime())) {
All good.

2023-05-18 12:05 UTC, bpaskali approved these changes

2023-05-18 12:06 UTC, merged