[VAL-8] Use DTOs in controllers
valconsee-internship/videotecha-ana pull request #6
Opened 2023-05-22 12:14 UTC by anagavrilovic

2023-05-22 12:15 UTC, anagavrilovic commented
![](https://github.trello.services/images/mini-trello-icon.png) [[VAL-8] Use DTOs in controllers](https://trello.com/c/JN2uIjq4/79-val-8-use-dtos-in-controllers)

2023-05-22 13:31 UTC, pantelicn requested changes

2023-05-22 13:31 UTC, pantelicn commented on src/main/java/com/example/videotecha/dto/ErrorDto.java
> +import java.sql.Timestamp;
This class is used within the JDBC API and probably shouldn't be used in your DTOs.

2023-05-23 08:45 UTC, pantelicn approved these changes

2023-05-23 08:46 UTC, merged